### ISSUE TITLE
Configuration messy

### ISSUE THREAD

**Issue by tedkirkpatrick** [sfu-innovation/cmpt-474#1]
The code in lib/app.js defining configuration files is messy. The config.default.json file should be advisory but the app.js code reads it in.  Then the code tries to read ./config/index.json, unless that has been overridden on the command line.  Lastly, the port is set by an environment variable defined in start.sh.

We need a real config/index.json (or config.json) that is separately version-controlled, as part of the system configuration. The port should be defined there rather than in start.sh.

**Comment by izaakschroeder** [comment]
Building better apps this year has led me to this: http://12factor.net/ (read section on config) and using .env files for configuration and `foreman` to spin up processes with those environment variables. It's quite a bit more flexible. Generally speaking you have a `/share/env/production.env` and `/share/env/development.env` which contain boilerplate for those environments. You then simply `cp /share/env/production.env /.env` and edit the file to be whatever you'd like. The port should definitely be in there. There is some argument against having the configuration itself version controlled (since now you're coupling an _instance_ of the application with the application itself). You could be free to have a separate repo that holds the config though if you wanted.

**Comment by tedkirkpatrick** [comment]
Fixed on GitLab version.

**Comment by izaakschroeder** [comment]
Invite me as collab on gitlab version?

**Comment by tedkirkpatrick** [comment]
On Jan 5, 2015, at 2:53 AM, Izaak Schroeder notifications@github.com wrote:

> Invite me as collab on gitlab version?

I can only invite valid SFU accounts (our GitLab is CAS-authenticated).  mis2 doesn’t seem to be known.  Has it been deleted?
Ted

**Comment by izaakschroeder** [comment]
Shouldn't be... I just logged into Fraser today.

**Comment by tedkirkpatrick** [comment]
Try signing in to SFU GitLab:

```
https://csil-git1.cs.surrey.sfu.ca/
```

Create a profile, etc. and maybe then I can find you.

Ted

**Comment by izaakschroeder** [comment]
GOT IT TEAM.
